apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-metric-server
  namespace: dev
  labels:
    app: rabbitmq-metric-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-metric-server
  template:
    metadata:
      labels:
        app: rabbitmq-metric-server
    spec:
      containers:
        - name: rabbitmq-metric-server
          image: rabbitmq-metric-server:0.1
          #resources: TODO: Add resources
          #  limits:
          #    cpu: 0.1
          #    memory: 32Mi
          ports:
            - containerPort: 5000
          env:
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "5000"
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-configmap
                  key: host
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-configmap
                  key: api_port
            - name: RABBITMQ_VHOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-configmap
                  key: virtual_host
            - name: RABBITMQ_LOGIN
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: LOGIN
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: PASSWORD