apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: dev
data:
  default.conf: |
    server {
       listen               443 ssl;
       server_name          localhost;
       ssl_certificate      /etc/nginx/ssl/tls.crt;
       ssl_certificate_key  /etc/nginx/ssl/tls.key;
       location / {
           proxy_pass http://localhost:5000/;
       }
    }