apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-metric-server
  namespace: dev
  labels:
    app: rabbitmq-metric-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-metric-server
  template:
    metadata:
      labels:
        app: rabbitmq-metric-server
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: nginx-secret
        - name: config-volume
          configMap:
            name: nginx-configmap
            items:
              - key: default.conf
                path: default.conf
      containers:
        - name: nginx
          image: nginx:1.19.7
          ports:
            - containerPort: 443
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/nginx/ssl
            - name: config-volume
              mountPath: /etc/nginx/conf.d/
        - name: rabbitmq-metric-server
          image: rabbitmq-metric-server:1.0
          resources:
            limits:
              cpu: 0.1
              memory: 64Mi
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 3
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-configmap
                  key: host
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-configmap
                  key: api_port
            - name: RABBITMQ_VHOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-configmap
                  key: virtual_host
            - name: RABBITMQ_LOGIN
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: LOGIN
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: PASSWORD