apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-metric-server
  namespace: dev
  labels:
    app: rabbitmq-metric-server
spec:
  selector:
    app: rabbitmq-metric-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5000