apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: consumer-app-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Object
      object:
        target:
          kind: Service
          name: rabbitmq-metric-server
        metricName: people_queue_messages
        targetValue: 20