apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-configmap
  namespace: dev
data:
  host: "rabbitmq"
  port: "5672"
  virtual_host: 'dev'
  definitions.json: |
    {
     "rabbit_version": "3.8.9",
     "users": [
      {
       "name": "dev_user",
       "password_hash": "q5lzzTONASWgosGBd4yRY8au/Wsu4gjlrq6U/nPz1cBX1lDs",
       "hashing_algorithm": "rabbit_password_hashing_sha256",
       "tags": ""
      }
     ],
     "vhosts": [
      {
       "name": "dev"
      }
     ],
     "permissions": [
      {
       "user": "dev_user",
       "vhost": "dev",
       "configure": ".*",
       "write": ".*",
       "read": ".*"
      }
     ],
     "parameters": [],
     "policies": [],
     "queues": [],
     "exchanges": [],
     "bindings": []
    }